### ISSUE TITLE
Is an XML file necessary?

### ISSUE THREAD

**Issue by syy-create** [fuscc-deep-path/sc_MTOP#11]
Is an XML file necessary? If there is no XML file, can the organization area be automatically selected for feature extraction

**Comment by uzuki11** [comment]
Do you have the result? If there is no XML file, how to proceed?

**Comment by CDPDisk** [comment]
> Do you have the result? If there is no XML file, how to proceed?

You can use ImageScope software to outline the ROI regions and export the corresponding xml. if the xml is not provided when extracting the features, then it will calculate all the regions.

**Comment by uzuki11** [comment]
Thank you for your guidance. To clarify, I modified utils_xml.py by commenting out line 176 `raise OSError('xml file is not exist')` and uncommenting line 177 `window_bbox = [[[0, 0], [wsi.level_dimensions[0][0], wsi.level_dimensions[0][1]]]]` to set `window_bbox `directly from image dimensions when XML parameters are unavailable. However, this change introduced an 
`{'feature_path': './feature6/16-HE', 'wsi_path': './image6/16-HE.tiff', 'xml_path': ''}
Traceback (most recent call last):
  File "main.py", line 89, in <module>
    fun4(**sub_args)
  File "/home/wcz/sc_MTOP/F4_Visualization.py", line 6, in fun4
    img_maker.read_csv(feature_path, wsi_path, xml_path, omit_edge=['N-N', 'T-N', 'I-N', 'S-N'], omit_cell=[5])
  File "/home/wcz/sc_MTOP/utils_xml.py", line 263, in read_csv
    name_inbox_tab[inbox_name] = True
IndexError: index 385543 is out of bounds for axis 0 with size 385543`   
Could you please advise on this issue?  Any insights into debugging this alignment or identifying mismatches between XML-derived and image-based dimensions would be greatly appreciated.

**Comment by uzuki11** [comment]
Runs perfectly through ImageScope, thanks for the suggestion.
