### ISSUE TITLE
F4可视化

### ISSUE THREAD

**Issue by 0link87** [fuscc-deep-path/sc_MTOP#9]
我想请教一下，我对自己的数据运行F4_Visualization时，出现了下面的错误：
Traceback (most recent call last):
File "sc_MTOP/main.py", line 89, in
fun4(**sub_args)
File "/root/sc_MTOP/F4_Visualization.py", line 6, in fun4
img_maker.read_csv(feature_path, wsi_path, xml_path, omit_edge=['N-N', 'T-N', 'I-N', 'S-N'], omit_cell=[5])
File "/root/sc_MTOP/utils_xml.py", line 225, in read_csv
offset = window_bbox[group, 0:1, :]
IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed
麻烦能否指导一下

**Comment by 0link87** [comment]
我用自己的mrxs的图片在运行F4_Visualization时，并用imagescope产生xml文件，还是出现上述一样的错误。我想再请教一下这该如何解决。

**Comment by CDPDisk** [comment]
这个问题看下来不太清楚是哪里出了问题，需要你那里自己进行调试才能找到问题。如果程序正常运行，window_bbox应该是一个N×2×2的矩阵，用来保存每个框型标记的左上角坐标和左下角坐标，但是根据你的报错只获得了一个一维向量。为什么只产生了这个一维向量应该需要你那里对代码进行debug才能发现问题了，我这边提供不了什么帮助

**Comment by 0link87** [comment]
你好我产生的csv文件截图如下
![1715435599507](https://github.com/fuscc-deep-path/sc_MTOP/assets/167217829/6e229114-cc53-4be3-9ad8-c3a5c09bc9cd)
和你们之前提供的示例产生的csv文件好像没有什么不同，就是不知道为什么会出现上述的错误

**Comment by 0link87** [comment]
你好，我用自己的mrxs的wsi进行可视化后最后结果就是xml文件限制区域的放大图，
![graph_slide-2019-04-01T11-31-42-R1-S1_plot0 (1)](https://github.com/fuscc-deep-path/sc_MTOP/assets/167217829/85948c81-b535-493d-b011-30deee8e61a8)
但是用svs的wsi时能实现结果，
![graph_TCGA-RC-A7SH-01Z-00-DX1_plot0](https://github.com/fuscc-deep-path/sc_MTOP/assets/167217829/26d42e4a-895d-43bf-b054-bfce93f73721)
请问一下，这是因为格式的问题吗？

**Comment by CDPDisk** [comment]
> 你好，我用自己的mrxs的wsi进行可视化后最后结果就是xml文件限制区域的放大图， ![graph_slide-2019-04-01T11-31-42-R1-S1_plot0 (1)](https://private-user-images.githubusercontent.com/167217829/329796281-85948c81-b535-493d-b011-30deee8e61a8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzYwODIsIm5iZiI6MTcxNTU3NTc4MiwicGF0aCI6Ii8xNjcyMTc4MjkvMzI5Nzk2MjgxLTg1OTQ4YzgxLWI1MzUtNDkzZC1iMDExLTMwZGVlZThlNjFhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNDQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODI5YjRlMGIxODM4YjRiYjg2ZGM1ZmE3NmQzNTdlMWMxMWYxMjI1NmY0YmRjM2U4YWM4MTRkMzcyYmUwYjNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.t-jdePvuwseGQLTtHIedphH13OijuTtKBSGP41MbJiI) 但是用svs的wsi时能实现结果， ![graph_TCGA-RC-A7SH-01Z-00-DX1_plot0](https://private-user-images.githubusercontent.com/167217829/329796323-26d42e4a-895d-43bf-b054-bfce93f73721.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1NzYwODIsIm5iZiI6MTcxNTU3NTc4MiwicGF0aCI6Ii8xNjcyMTc4MjkvMzI5Nzk2MzIzLTI2ZDQyZTRhLTg5NWQtNDNiZi1iMDU0LWJmY2U5M2Y3MzcyMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QwNDQ5NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMzAwY2FjNmMzZGEyZDliNDRmNmFlMTljMDQyNmY2N2I0ZjQ1ZmU5YTcwOGVjZTgyZDdhNDc5OTUyNGNkZjc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sz3RBtqHvQuzBHtfV4iD2ryNn-g27hXThtWJXRr2qXY) 请问一下，这是因为格式的问题吗？

 看起来像是mrxs格式导致的。mrxs格式跟普通切片格式不同，我们当时的可视化代码对mrxs也没有做特殊处理，确实是有可能出问题的

**Comment by LEZHOU26** [comment]
> 我想请教一下，我对自己的数据运行F4_Visualization时，出现了下面的错误： Traceback (most recent call last): File "sc_MTOP/main.py", line 89, in fun4(**sub_args) File "/root/sc_MTOP/F4_Visualization.py", line 6, in fun4 img_maker.read_csv(feature_path, wsi_path, xml_path, omit_edge=['N-N', 'T-N', 'I-N', 'S-N'], omit_cell=[5]) File "/root/sc_MTOP/utils_xml.py", line 225, in read_csv offset = window_bbox[group, 0:1, :] IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed 麻烦能否指导一下

我在用svs的时候遇到同样的问题，请问你改了什么地方能让他运行，谢谢

**Comment by 0link87** [comment]
> > 我想请教一下，我对自己的数据运行F4_Visualization时，出现了下面的错误： Traceback (most recent call last): File "sc_MTOP/main.py", line 89, in fun4(**sub_args) File "/root/sc_MTOP/F4_Visualization.py", line 6, in fun4 img_maker.read_csv(feature_path, wsi_path, xml_path, omit_edge=['N-N', 'T-N', 'I-N', 'S-N'], omit_cell=[5]) File "/root/sc_MTOP/utils_xml.py", line 225, in read_csv offset = window_bbox[group, 0:1, :] IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed 麻烦能否指导一下
> 
> 我在用svs的时候遇到同样的问题，请问你改了什么地方能让他运行，谢谢

in utils_xml.py,  if anno.get('LineColor') == '65280':       Modify the value in the statement to check if anno.get('LineColor') is equal to '65280'.

def get_windows(xml_path): 
    windows = []
    assert os.path.exists(xml_path), f"Can't find {xml_path}"
    tree = ET.parse(xml_path)
    annos = tree.getroot()
    
    # 遍历每个Annotation
    for anno in annos.findall('Annotation'):
        if anno.get('LineColor') == '65280':  # 过滤特定的Annotation
            for vs in anno.iter('Vertices'):
                vertices = []
                for v in vs.iter('Vertex'):
                    # 提取每个顶点的X, Y坐标
                    x = float(v.get('X'))
                    y = float(v.get('Y'))
                    vertices.append((x, y))  # 将顶点加入列表
                windows.append(vertices)  # 将多边形的顶点列表加入窗口列表
    return windows
